select * from jebinraja

1`. What is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount) as total_revenue
from jebinraja
group by gender

2. Which customer used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from jebinraja
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from jebinraja)

3. which are the top 5 products with the highest average review rating? 

SELECT item_purchased as Products,round(AVG(review_rating)::numeric,2) as Average_Review_Rating
FROM jebinraja
GROUP BY products
ORDER BY average_review_rating desc
LIMIT 5

4. Compare the average purchase amounts between standard and express shipping

select shipping_type as Shipping_Type,round(avg(purchase_amount),2) as Avg_Purchase
from jebinraja
where shipping_type in ('Standard','Express') --in aggregate function where should be before group by
--and if you are using having in aggregate function can use after the group by 
group by shipping_type

5. Do subscribed customers spend more? Compare average spend and total revenue 	between subscribers 
   and unsubscribers? 
SOLUTIONS: 

select subscription_status,
count(customer_id) as total_customers, 	
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from jebinraja
group by subscription_status
order by avg_spend,total_revenue desc)

6. Which 5 products have the highest percentage of purchases with discount applied?

solutions: 

select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as Discount_Rate
from jebinraja
group by item_purchased
order by Discount_Rate desc
limit 5

solutions 2: 
select item_purchased,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from jebinraja
group by item_purchased
order by raja desc
limit 5


7. Segment Customers into new, Returning and loyal based on their total number of previous purchases
   and show the count of each segment

with customer_type as (
select customer_id,previous_purchases,
   case when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
		else 'Loyal'
		end as customer_segment
from jebinraja
)
select customer_segment,count(*) as Count_Of_Each_Segment
from customer_type
group by customer_segment

8. What are the top 3 most purchased products within each category?

SOLUTIONS:

with item_count as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rn
from jebinraja
group by category,item_purchased
)
select item_rn,item_purchased,category,total_orders
from item_count
where item_rn <=3

9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(previous_purchases) as repeat_buyers
from jebinraja
where previous_purchases > 5
group by subscription_status

10. What is the revenue contribution of each age group?

select * from jebinraja

select age_group,sum(purchase_amount) as revenue_contribution
from jebinraja
group by age_group
order by  revenue_contribution desc





 

   




